name: Deploy IAC

on:
  workflow_call:
    inputs:
      doenv:
        required: true
        type: string
      workflowtype:
        required: true
        type: choice
        options:
          - ps
          - iac

jobs:
  deploy:
    runs-on: windows-latest
    environment: ${{  inputs.doenv  }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            devops
      - uses: actions/download-artifact@v4
        with:
          name: ${{  inputs.workflowtype  }}-build
      - name: Build ${{  inputs.workflowtype  }}
        shell: pwsh
        run: .\devops\${{  inputs.workflowtype  }}\deploy.ps1
        env:
          mode: 'plan'
          environment: 'WagnerTest'  