name: Deploy IAC

on:
  workflow_call:
    inputs:
      doenv:
        required: true
        type: string
      workflowtype:
        required: true
        type: string
      mode:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy ${{  inputs.workflowtype }} (${{  inputs.mode  }} mode)
    runs-on: windows-latest
    environment: ${{  inputs.doenv  }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            devops
            dat
      - uses: actions/download-artifact@v4
        with:
          name: ${{  inputs.workflowtype  }}-build
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{  secrets.AZURE_CLIENT_ID  }}
          tenant-id: ${{  secrets.AZURE_TENANT_ID  }}
          subscription-id: ${{  secrets.AZURE_SUB_ID  }}
      - name: Deploy ${{  inputs.workflowtype  }}
        shell: pwsh
        run: .\devops\${{  inputs.workflowtype  }}\deploy.ps1
        env:
          appEnv: ${{  vars.APP_ENVIRONMENT  }}
          doEnv: ${{  vars.DEVOPS_ENVIRONMENT  }}
          mode: ${{  inputs.mode  }}