#<DOC>
#Pipelines whose name begins with "template" are <a href='https://docs.github.com/en/actions/using-workflows/reusing-workflows' target='_blank'>
#reusable workflows</a> that are called by the main workflow. When called, the parameters declared under "inputs" 
#must be transferred.<br/>The template-deployswa pipeline is a special variant of the deploy pipeline. It is used 
#instead of the normal template-deploy workflow for the "doc" artefact type. Uploading content to a static web 
#app requires a special process with proprietary command line tools that cannot be executed in the normal context 
#of a worker agent. Therefore, a Docker container is started for this one job (deploy frontend), which performs 
#the upload.<br/>Other than that, the workflow does not differ from the normal template-deploy workflow.
#</DOC>
name: Deploy with SWA

on:
  workflow_call:
    inputs:
      doenv:
        required: true
        type: string
      workflowtype:
        required: true
        type: string
      mode:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy ${{  inputs.workflowtype }} (${{  inputs.mode  }} mode)
    runs-on: ubuntu-latest
    environment: ${{  inputs.doenv  }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            devops
      - uses: actions/download-artifact@v4
        with:
          name: ${{  inputs.workflowtype  }}-build
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{  secrets.AZURE_CLIENT_ID  }}
          tenant-id: ${{  secrets.AZURE_TENANT_ID  }}
          subscription-id: ${{  secrets.AZURE_SUB_ID  }}
      - name: Deploy ${{  inputs.workflowtype  }}
        shell: pwsh
        run: .\devops\${{  inputs.workflowtype  }}\deploy.ps1
        env:
          appEnv: ${{  vars.APP_ENVIRONMENT  }}
          doEnv: ${{  vars.DEVOPS_ENVIRONMENT  }}
          mode: ${{  inputs.mode  }}
      - name: Deploy frontend
        id: build-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWATOKEN }}
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          app_location: doc          