name: Deploy IAC

on:
  workflow_call:
    inputs:
      artifactname:
        required: true
        type: string

jobs:
  deploy:
    runs-on: windows-latest
    environment: integration-plan
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            devops
      - uses: actions/download-artifact@v4
        with:
          name: ${{  inputs.artifactname  }}
      - name: Build iac
        shell: pwsh
        run: .\devops\iac\deploy.ps1
        env:
          mode: 'plan'
          environment: 'WagnerTest'  