#<DOC>
#Pipelines whose name begins with "template" are <a href='https://docs.github.com/en/actions/using-workflows/reusing-workflows' target='_blank'>
#reusable workflows</a> that are called by the main workflow. When called, the paratemeters declared 
#under "inputs" must be transferred.<br/>The template-detect-change workflow is used to find out in which 
#artefact folders of the repository content has changed. This information is used in the deploy pipeline 
#to execute individual jobs or not, depending on whether this is necessary due to the changes in the 
#current commit or not.<br/>The pipeline uses a 3rd party marketplace Github action (dorny/paths-filter) for its function.
#</DOC>
name: Detect change in repos

on:
  workflow_call:
    outputs:
      iac:
        value: ${{  jobs.paths-filter.outputs.iac  }}
      ps:
        value: ${{  jobs.paths-filter.outputs.ps  }}
      dat:
        value: ${{  jobs.paths-filter.outputs.dat  }}

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      iac: ${{ steps.filter.outputs.iac }}
      ps: ${{ steps.filter.outputs.ps }}
      dat: ${{ steps.filter.outputs.dat }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          iac:
            - 'iac/**'
          ps:
            - 'ps/**'
          dat:
            - 'dat/**'
        base: ${{ github.ref }}