name: Build code artifacts

on:
  workflow_call:
    inputs:
      artifacttype:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ inputs.artifacttype }}
        shell: pwsh
        run: .\devops\${{  inputs.artifacttype  }}\build.ps1
        env:
          appEnv: ${{  vars.APP_ENVIRONMENT  }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{  inputs.artifacttype }}-build
          path: deployment\${{ inputs.artifacttype }}\**
          retention-days: 5
