name: Detect change in repos

on:
  workflow_call:
    outputs:
      iac:
        value: ${{  jobs.paths-filter.outputs.iac  }}
      ps:
        value: ${{  jobs.paths-filter.outputs.ps  }}
      dat:
        value: ${{  jobs.paths-filter.outputs.dat  }}

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      iac: ${{ steps.filter.outputs.iac }}
      ps: ${{ steps.filter.outputs.ps }}
      dat: ${{ steps.filter.outputs.dat }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          iac:
            - 'iac/**'
          ps:
            - 'ps/**'
          dat:
            - 'dat/**'
        base: ${{ github.ref }}