#<DOC>
#Pipelines whose name begins with "template" are 
#<a href='https://docs.github.com/en/actions/using-workflows/reusing-workflows' target='_blank'>
#reusable workflows</a> that are called by the main workflow. When called, the parameters 
#declared under "inputs" must be transferred.<br/>The template-build pipeline performs the 
#build task for all artefacts. Corresponding 
#<a href='https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts' target='_blank'>
#Github Actions artefacts</a> are created and saved in the context of the workflow. These artefacts are used 
#in the later plan and build phases.<br/>In addition to specific elements, the artefacts created contain 
#2 Powershell scripts per type (plan.ps1 and apply.ps1), which in turn contain the code for the corresponding 
#phases.<br/>The build phase is the only phase in which the entire repository is loaded onto the Pipeline Worker. 
#When building the Github Actions artefacts, no 3rd party marketplace extensions are used and the pipeline 
#does not establish any connections to other systems. This isolation ensures that the build is secure.
#</DOC>
name: Build code artifacts

on:
  workflow_call:
    inputs:
      doenv:
        required: true
        type: string
      artifacttype:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.artifacttype }} artifact
    runs-on: windows-latest
    environment: ${{  inputs.doenv  }}
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ inputs.artifacttype }}
        shell: pwsh
        run: .\devops\${{  inputs.artifacttype  }}\build.ps1
        env:
          appEnv: ${{  vars.APP_ENVIRONMENT  }}
          doEnv: ${{  vars.DEVOPS_ENVIRONMENT  }}
          dpDir: deployment\${{ inputs.artifacttype }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{  inputs.artifacttype }}-build
          path: deployment\${{ inputs.artifacttype }}\**
          retention-days: 5
