name: 'deploy iac'

on:
  push:
    branches:
      - 'feature/**'

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      iac: ${{ steps.filter.outputs.iac }}
      ps: ${{ steps.filter.outputs.ps }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          iac:
            - 'iac/**'
          ps:
            - 'ps/**'

  next-job:
    runs-on: windows-latest
    # Wait from the paths-filter to be completed before starting next-job
    needs: paths-filter
    if: needs.paths-filter.outputs.iac == 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Integration-plan
      shell: pwsh
      run: .\script1.ps1
      env:
          environment: 'Integration'
  













jobs:
  deploy iac:
