name: 'deploy iac'

on:
  push:
    branches:
      - 'feature/**'

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      iac: ${{ steps.filter.outputs.iac }}
      ps: ${{ steps.filter.outputs.ps }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          iac:
            - 'iac/**'
          ps:
            - 'ps/**'

  next-job:
    runs-on: windows-latest
    needs: paths-filter
    steps:
    - uses: actions/checkout@v3
    - name: Build iac
      if: needs.paths-filter.outputs.iac == 'true'
      shell: pwsh
      run: .\devops\iac\deploy.ps1
      env:
          environment: 'Integration'

  third-job:
    runs-on: windows-latest
    needs: [paths-filter, next-job]
    steps:
    - uses: actions/checkout@v3
    - name: Build ps
      if: needs.paths-filter.outputs.ps == 'true'
      shell: pwsh
      run: .\devops\ps\deploy.ps1
      env:
          environment: 'Integration'
    